f1 = open('fil1.txt', 'r') 
f2 = open('fil2.txt', 'w') 
lines = f1.readlines() 
type(lines) 
for i in range(0, len(lines)):
    if(i % 2 != 0):
        f2.write(lines[i]) 
f1.close()
f2.close() 
f1 = open('file1.txt', 'r') 
f2 = open('file2.txt', 'r') 
str1 = f1.read()
str2 = f2.read()
print("file1 content...")
print(str1)
print()
print("file2 content...")
print(str2)
f1.close()
f2.close()
